languageCode = "en-us"
title = "Curtis Timson"
theme = "hugo-theme-bleak-ct"
baseurl = "https://deploy-preview-33--curtistimson.netlify.com/"
Paginate = 20



[params]
  # Warning Keys are case sensitives
  Subtitle = "software developer"
  cover = "images/cover.jpg"
  # Google analytics
  googleAnalyticsUserID = "UA-50505111-2"
  disqus = "curtis-timson"

  [params.author]
    firstName = "Curtis"
    lastName = "Timson"
    gender = "male"
    userName = "curt"
    image = "//www.gravatar.com/avatar/15a556c8b58e8aefa727088885925a12.png"
    website = "https://curtistimson.co.uk"
    twitter = "curty_"
    github = "curttimson"
    linkedin = "curtistimson"
    gravatarHash = "15a556c8b58e8aefa727088885925a12"
